---
- name: restart webserver
  service:
    name: "{{ php_webserver_daemon }}"
    state: restarted
  become: yes
  notify: restart php-fpm
  when: php_enable_webserver | bool

- name: restart php-fpm
  service:
    name: "{{ php_fpm_daemon }}"
    state: restarted
  become: yes
  when: php_enable_php_fpm | bool
